# GitLab user. git by default
user: git

{% set root_dir = salt['pillar.get']('gitlab:lookup:root_dir', '/home/git') %}
{% set repo_dir = salt['pillar.get']('gitlab:lookup:repo_dir', root_dir ~ '/repositories') %}
{% set logs_dir = salt['pillar.get']('gitlab:lookup:logs_dir', root_dir ~ '/logs') %}

# Url to gitlab instance. Used for api calls. Should end with a slash.
{%- if salt['pillar.get']('gitlab:https', false) %}
gitlab_url: "https://{{ salt['pillar.get']('gitlab:hostname', grains['fqdn']) }}/"
{% else %}
gitlab_url: "http://{{ salt['pillar.get']('gitlab:hostname', grains['fqdn']) }}/"
{% endif %}

http_settings:
#  user: someone
#  password: somepass
{%- if salt['pillar.get']('gitlab:shell:ca_file', false) %}
  ca_file: {{salt['pillar.get']('gitlab:shell:ca_file') }}
{% endif %}
{%- if salt['pillar.get']('gitlab:shell:ca_path', false) %}
  ca_path: {{ salt['pillar.get']('gitlab:shell:ca_path') }}
{% endif %}
  self_signed_cert: {{ salt['pillar.get']('gitlab:shell:self_signed_cert', false) }}

# Repositories path
# Give the canonicalized absolute pathname,
# REPOS_PATH MUST NOT CONTAIN ANY SYMLINK!!!
# Check twice that none of the components is a symlink, including "/home".
repos_path: "{{ repo_dir }}"

# File used as authorized_keys for gitlab user
auth_file: "{{ root_dir }}/.ssh/authorized_keys"

# File that contains the secret key for verifying access to GitLab.
# Default is .gitlab_shell_secret in the root directory.
secret_file: "{{ salt['pillar.get']('gitlab:shell:secret:path', '/opt/git/.gitlab_shell_secret') }}"

# Redis settings used for pushing commit notices to gitlab
redis:
  bin: /usr/bin/redis-cli
  host: 127.0.0.1
  port: 6379
  # socket: /tmp/redis.socket # Only define this if you want to use sockets
  namespace: resque:gitlab

# Log file.
# Default is gitlab-shell.log in the root directory.
log_file: "{{ logs_dir }}/gitlab-shell.log"

# Log level. INFO by default
log_level: {{ salt['pillar.get']('gitlab:shell:log_level', 'INFO') }}

# Audit usernames.
# Set to true to see real usernames in the logs instead of key ids, which is easier to follow, but
# incurs an extra API call on every gitlab-shell command.
audit_usernames: {{ salt['pillar.get']('gitlab:shell:audit_usernames', false) }}

